# Generated by Django 6.0.3 on 2026-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institutional_id',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
