# Generated by Django 6.0.3 on 2026-05-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_id_photo_customuser_institutional_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseprofile",
            old_name="faculty",
            new_name="department",
        ),
    ]
