# Generated by Django 6.0.3 on 2026-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
