# Generated by Django 6.0.3 on 2026-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0002_grievance_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
